version: '3.8'

services: 
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: root
      POSTGRES_DB: class_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks: 
      class_net:
        ipv4_address: 172.0.10.10
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    depends_on: 
      db:
        condition: service_healthy
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks: 
      class_net:
        ipv4_address: 172.0.10.20
    healthcheck:
      test: ["CMD-SHELL", "curl", "-f", "http://localhost:5050/misc/ping"]
      interval: 30s
      timeout: 15s
      retries: 5
volumes: 
  postgres-data:
  pgadmin-data:
networks: 
  class_net:
    ipam:
      config: 
        - subnet: "172.0.10.0/24"
          gateway: 172.0.10.1